### ISSUE TITLE
Build fails with node-canvas 1.2.0 dependency

### ISSUE THREAD

**Issue by ekynoxe** [skyglobal/Sheut#5]
node-canvas was updated to 1.2.0 over the weekend, which is now causing the installation of our dependencies to fail. I have forked the project and pinned the version of node-canvas to 1.1.*, which resolves the issue, but it would be good to use the latest version if possible. Here is the error I encountered:

**npm i canvas**

```
make: Entering directory `/home/build/jenkins/jobs/build-rpm/workspace/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node: Finished
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:8:
../src/PNG.h: In function ‘cairo_status_t canvas_write_png(cairo_surface_t*, void (*)(png_struct*, png_byte*, png_size_t), void*)’:
../src/PNG.h:165: warning: case label value is less than minimum value for type
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc: In member function ‘void Context2d::shadow(void (*)(cairo_t*))’:
../src/CanvasRenderingContext2d.cc:378: error: ‘cairo_surface_create_similar_image’ was not declared in this scope
make: *** [Release/obj.target/canvas/src/CanvasRenderingContext2d.o] Error 1
make: Leaving directory `/home/build/jenkins/jobs/build-rpm/workspace/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 2.6.32-431.29.2.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/build/jenkins/jobs/build-rpm/workspace/node_modules/canvas
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 2.6.32-431.29.2.el6.x86_64
npm ERR! argv "node" "/usr/bin/npm" "i" "canvas"
npm ERR! node v0.10.33
npm ERR! npm  v2.4.1
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/build/jenkins/jobs/build-rpm/workspace/npm-debug.log
```

There is an open issue on the node canvas github project about this:  https://github.com/Automattic/node-canvas/issues/509

Until this issue is fixed, I'd advise pinning the canvas dependency to the minor revision (~ instead of ^), as shown in this [pull request](https://github.com/skyglobal/Sheut/pull/6)

Cheers

**Comment by ekynoxe** [comment]
This has been fixed with https://github.com/skyglobal/Sheut/pull/9, closing.
